# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Cool Website # <--- CHANGE THIS
email: your-email@domain.com # <--- CHANGE THIS (Optional, used by some themes)
description: >- # <--- CHANGE THIS (Appears in search results)
  A repository of random essays and useful websites I find.
baseurl: "" # the subpath of your site, e.g. /blog. Leave blank for username.github.io
url: "https://your-username.github.io" # <--- CHANGE THIS to your site's domain
github_username: your-username # <--- CHANGE THIS (Optional, used by some themes)

# Use the Minima theme, fetched remotely for simplicity with GitHub Pages
      
remote_theme: jekyll/minima@v2.5.1

    
# Minima theme settings (optional, check Minima docs for more)
minima:
  # Minima skins: air, classic, dark, default, solarized-dark, solarized-light
  skin: default
  # Social links - add username per platform (optional)
  # twitter_username: your_twitter
  # github_username:  your_username
  # linkedin_username: your_linkedin

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Use GitHub Flavored Markdown
  hard_wrap: false

# Define the 'websites' collection for your useful links
collections:
  websites:
    output: true # Generate individual pages for each website entry
    permalink: /websites/:title/ # URL structure for individual website pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Plugins - GitHub Pages supports these by default, no extra Gemfile needed for basic Minima
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# FUTURE USE: If you need plugins NOT supported by default on GH Pages,
# you'll need a Gemfile and likely a GitHub Action for building.
# For now, we stick to native capabilities.
